# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(141413)
$foreground = rgb(F4F3F3)
$color0 = rgb(3C3B3B)
$color1 = rgb(B55C24)
$color2 = rgb(BD6127)
$color3 = rgb(BE6224)
$color4 = rgb(BE6326)
$color5 = rgb(9E9D9B)
$color6 = rgb(A7A6A6)
$color7 = rgb(E6E6E5)
$color8 = rgb(A1A1A1)
$color9 = rgb(F17A30)
$color10 = rgb(FD8134)
$color11 = rgb(FE8230)
$color12 = rgb(FD8433)
$color13 = rgb(D3D1CF)
$color14 = rgb(DFDEDD)
$color15 = rgb(E6E6E5)
