# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D4D3D3
background         #873A09
cursor             #B0724C

active_tab_foreground     #873A09
active_tab_background     #D4D3D3
inactive_tab_foreground   #D4D3D3
inactive_tab_background   #873A09

active_border_color   #D4D3D3
inactive_border_color #873A09
bell_border_color     #A7A6A6

color0      #A1A1A0
color1		#A7A6A6
color2		#9E9D9B
color3		#BE6326
color4		#BE6224
color5		#BD6127
color6		#B55C24
color7		#646463
color8		#9C9B9B
color9		#DFDEDD
color10		#D3D1CF
color11		#FD8433
color12		#FE8230
color13		#FD8134
color14		#F17A30
color15		#E6E6E5
